### GET ALL
GET http://localhost:8080/bookings/ HTTP/1.1
Content-Type: application/json

### REGISTER
POST http://localhost:8080/bookings/ HTTP/1.1
Content-Type: application/json

{
    "user_id": "62aa220d1af1fa1be71d38dc",
    "showtime_id": "62aadb5f0b492e3a9b3e0e28",
    "movies": [
        "62aad5601136b55656bd6692",
        "62aad955bc7b8c454950d6c7"
    ]
}

### FIND BY ID
GET http://localhost:8080/bookings/62aade864a870b24d2523f42 HTTP/1.1
Content-Type: application/json

### UPDATE
PUT http://localhost:8080/bookings/62aade864a870b24d2523f42 HTTP/1.1
Content-Type: application/json

{
    "user_id": "62aa220d1af1fa1be71d38dc",
    "showtime_id": "62aadb5f0b492e3a9b3e0e28",
    "movies": [
        "62aad5601136b55656bd6692",
        "62aad955bc7b8c454950d6c7"
    ]
}

### DELETE
DELETE http://localhost:8080/bookings/000000000000000000000000 HTTP/1.1
Content-Type: application/json